config/routes.rb
Breezedigs::Application.routes.draw do

  root to: 'static_pages#home'

  match "/sitemap.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3
  match "/sitemapa.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  ActiveAdmin.routes(self)

  resources :users do
    collection do
      get :manager
      get :tenant
    end
  end

  get 'reviews/selectbuilding' => 'reviews#selectbuilding', :as => :selectbuilding
  get 'rents/selectbuilding' => 'rents#selectbuildingrent', :as => :selectbuildingrent
  get 'photos/selectbuilding' => 'photos#selectbuildingphoto', :as => :selectbuildingphoto
  get 'floorplans/selectbuilding' => 'floorplans#selectbuildingfloorplan', :as => :selectbuildingfloorplan
  get 'buildings/update_areas' => 'buildings#update_areas', :as => :update_areas
  get 'buildings/update_neighborhoods' => 'buildings#update_neighborhoods', :as => :update_neighborhoods

  resources :reviews
  resources :rents
  resources :floorplans
  resources :photos
  resources :cities

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :buildings do
    resources :reviews
    resources :rents
    resources :floorplans
    resources :photos
  end

  resources :neighborhoods

  match '/terms', to: 'static_pages#terms'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/how-it-works', to: 'static_pages#how'
  match '/careers', to: 'static_pages#careers'
  match '/press', to: 'static_pages#press'
  match '/partners', to: 'static_pages#partners'
  match '/privacy', to: 'static_pages#privacy'
  match '/advertise', to: 'static_pages#advertise'
  match '/managers', to: 'static_pages#managers'
  match '/guidelines', to: 'static_pages#guidelines'
  match '/abuse', to: 'static_pages#abuse'
  match '/allcities', to: 'static_pages#allcities'

  match '/signup', to: 'users#sign_up'
  match '/signin', to: 'sessions#sign_in'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role, :avatar, :first_name, :last_name, :email, :password, :password_confirmation, :remember_me, :status, :provider, :uid
  # attr_accessible :title, :body
  has_attached_file :avatar, styles:
  { medium: "300x300>", thumb: "100x100>" }, 
  default_url: "profileplaceholder.png"

  has_many :reviews
  has_many :rents
  has_many :photos
  has_many :buildings

  validates :email,         uniqueness: true

  def self.from_omniauth(auth) #Takes the auth params from external provider and parses the data to create a new user
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      fullname = auth.info.name.split(' ')
      user.first_name = fullname[0]
      user.last_name = fullname[1]
      user.email = auth.info.email ? auth.info.email : ""
    end
  end

  def self.new_with_session(params, session) #Overrides Devise method by same name
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required? # Skips the password validation for creating a user if an external auth is used
    super && provider.blank?
  end

  def email_required? # Skips the email validation for creating a user if an external auth is used
    super && provider.blank?
  end

  def update_with_password(params, *options) # If user edits their profile after using external authentication, hides the current password field
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	skip_before_filter :verify_authenticity_token

	def show
		@user = User.find(params[:id])
		@reviews = @user.reviews
		@rents = @user.rents
		@photos = @user.photos
		@buildings = @user.buildings
	end

	def index
	end

	def create
		@user = User.create(params[:user])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			redirect_to current_user
		else
			render :action => 'edit'
		end
	end

	def new
	end

	def edit
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.delete
		redirect_to root_path
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def show_reviews(user)
		has_reviews = user.reviews.is_blank?

		if reviews?

		else
			raw("<h3>You have not written a review yet</h3>").html_safe
			raw(link_to(raw("<button class=\"btn btn-primary btn-large\">Write a review</button>"), new_review_path)).html_safe
		end
	end

	def gravatar_for(user, options = { size:90 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase) #converts to gravatar-readble id
		size = options[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
		image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
	end
end

app/views/users/_profile_header.html.erb
<div class="profile-header">

		<div class="buffer-small"></div>	
	
		<ul class="profile-header no-wrap">
			<li id="avatar">
				<%= gravatar_for @user %>
			</li>

			<li id="user-section">
				<h1><%= @user.first_name %></h1>
				<h2><%= @user.last_name %></h2>
				<h3><%= @user.email %></h3>
				<%= link_to "Change your Gravatar", "http://en.gravatar.com/emails/" %>
			</li>

app/views/users/edit.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'users' %>
<% end %>

<% provide(:title, 'My Account') %>

<div class="bg-texture-wrapper">
<div class="container">
  <%= render 'users/profile_header' %>
        <!-- Code snipped from partial above to be able to manually adjust which buttons i highlgihted depending on the view -->
        <li id="user-links">
        <ul class="profile-nav">
          <li>
            <%= link_to "My Account", user_path(current_user), class: "prof-btn" %>
          </li>
          <li>
            <%= link_to "Edit Profile & Settings", edit_user_path(current_user), class: "prof-btn selected-btn" %>
          </li>
        </ul>
      </li>
    </ul>
  </div>
  <div class="em-buffer-2"></div>
    <!--
    <div class="user-settings">
      <h2>Edit Email Settings</h2>
    </div>
    -->

    <div class="edit-box">
      <h2>Edit your profile</h2>
      <%= form_for(@user) do |f| %>
        <%= devise_error_messages! %>

        <div><p>First Name</p>
        <%= f.text_field :first_name, :autofocus => true, class: "edit-field" %></div>

        <div><p>Last Name</p>
        <%= f.text_field :last_name, :autofocus => true, class: "edit-field" %></div>

        <div><p>Email</p>
        <%= f.email_field :email, :autofocus => true, class: "edit-field" %></div>

        <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
        <% end %>

        <div><p>Password <i>(leave blank if you don't want to change it)</i></p>
        <%= f.password_field :password, :autocomplete => "off", class: "edit-field" %></div>

        <div><p>Password Confirmation</p>
        <%= f.password_field :password_confirmation, class: "edit-field" %></div>

        <% if f.object.encrypted_password.present? %>
          <div><p>Current Password <i>(we need your current password to confirm your changes)</i></p>
          <%= f.password_field :current_password, class: "edit-field" %></div>
        <% end %>

        <div><%= f.submit "Update", class: "btn" %></div>
      <% end %>

      <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete, class: "btn" %></p>

      <%= link_to "Back", :back %>

    </div>
</div>
</div>

<div class="buffer"></div>

app/views/users/manager.js.erb
$('#user_role').val('manager')

app/views/users/show.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'users' %>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag "static_helpers" %>
<% end %>

<% provide(:title, 'My Account') %>

<%= render 'layouts/facebooklikebox' %>

<div class="container">
	
	<%= render 'profile_header' %>
	<!-- Code snipped from partial above to be able to manually adjust which buttons i highlgihted depending on the view -->
		    <li id="user-links">
	        <ul class="profile-nav">
	          <li>
	            <%= link_to "My Account", user_path(current_user), class: "prof-btn selected-btn" %>
	          </li>
	          <li>
	            <%= link_to "Edit Profile & Settings", edit_user_path(current_user), class: "prof-btn" %>
	          </li>
	        </ul>
	      </li>
	    </ul>
	  </div>

	<div class="profile-content-area">
		<div class="contributions">
			<!-- user-contribution class used for reviews, rents, & photos -->
			<div class="user-contributions">
				<div class="contributions-header">
					<h2>Your Reviews</h2>
					<%= link_to "Write a new review", new_review_path %>
				</div>
				<% if @reviews.nil? || @reviews.blank? %>
					<p>You have not written any reviews yet</p>
				<% else %>
					<ul>
						<% @reviews.each do |review| %>
							<li>
								<div id="user-content-each">
									<h4><%= link_to review.building.name, building_path(review.building) %><span id="building-address-text">, <%= review.building.address %></span></h4>
							<%= raw("
								<p><span>Pros:</span> #{review.pros}</p>
								<p><span>Cons:</span> #{review.cons}</p>
							") %>
								</div>
								<div id="user-edit-link">
							<%= link_to "Edit Review", edit_review_path(review), id: "font-082em" %><br>
							<%= link_to "Delete Review", review_path(review), confirm: "Are you sure?", method: :delete, id: "font-082em" %>
								</div>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>

			<div class="user-contributions margin-top-1em">
				<div class="contributions-header">
					<h2>Rents You've Submitted</h2>
					<%= link_to "Add a new rent", new_rent_path %>
				</div>
				<% if @rents.nil? || @rents.blank? %>
				<p>You have not submited a rent yet</p>
				<% else %>
					<ul>
						<% @rents.each do |rent| %>
							<li>
								<div id="user-content-each">
								<h4><%= link_to rent.building.name, building_path(rent.building) %><span id="building-address-text">, <%= rent.building.address %></span></h4>
							<%= raw("
								<p><span>Rent:</span> #{rent.rent}</p>
								<p><span>Utilities:</span> #{rent.utilities}</p>
							") %>
								</div>
								<div id="user-edit-link">
							<%= link_to "Edit rent", edit_rent_path(rent), id: "font-082em" %><br>
							<%= link_to "Delete rent", rent_path(rent), confirm: "Are you sure?", method: :delete, id: "font-082em" %>
								</div>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>

			<div class="user-contributions margin-top-1em">
				<div class="contributions-header">
					<h2>Photos You've Added</h2>
					<%= link_to "Add a new photo", new_photo_path %>
				</div>
				<% if @photos.nil? || @photos.blank? %>
				<p>You have not uploaded a photo yet</p>
				<% else %>
					<ul>
						<% @photos.each do |photo| %>
							<li>
								<div id="user-content-each">
								<h4><%= link_to photo.building.name, building_path(photo.building) %><span id="building-address-text">, <%= photo.building.address %></span></h4>
								<%= image_tag photo.image.url, width: "200px" %>
								</div>
								<div id="user-edit-link">
							<%= link_to "Edit photo", edit_photo_path(photo), id: "font-082em" %><br>
							<%= link_to "Delete photo", photo_path(photo), confirm: "Are you sure?", method: :delete, id: "font-082em" %>
								</div>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>

			<div class="user-contributions margin-top-1em">
				<div class="contributions-header">
					<h2>Buildings You've Added</h2>
					<%= link_to "Add a new building", new_building_path %>
				</div>
				<% if @buildings.nil? || @buildings.blank? %>
					<p>You have not added a building</p>
				<% else %>
					<ul>
						<% @buildings.each do |building| %>
							<li>
								<div id="user-content-each">
								<h4><%= link_to building.name, building_path(building) %><span id="building-address-text"> | <%= building.address %>, <%= building.zip %></span></h4>
								<p><%= geogrify(building) %></p>
								</div>
								<div id="user-edit-link">
								</div>
							</li>
						<% end %>
					</ul>
				<% end %>
			</div>

		</div>

		<div class="user-sidebar">
			<h5>Thank you for contributing to our community</h5>
			<p>The reviews, rental data, and photos you submit add to a growing collection of information that will make the rental process easier and hold agents and landlords accountable for providing better living conditions and playing by the rules.</p>
			<p>Please take a moment to Like our site with your friends to help us in our mission:</p>
			<div class="fb-like-box" data-href="https://www.facebook.com/breezedigs" data-width="190" data-show-faces="false" data-stream="false" data-show-border="false" data-header="false"></div>
		</div>

	</div>
</div>

app/views/users/tenant.js.erb
$('#user_role').val('tenant')