config/routes.rb
Breezedigs::Application.routes.draw do

  root to: 'static_pages#home'

  match "/sitemap.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3
  match "/sitemapa.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  ActiveAdmin.routes(self)

  resources :users do
    collection do
      get :manager
      get :tenant
    end
  end

  get 'reviews/selectbuilding' => 'reviews#selectbuilding', :as => :selectbuilding
  get 'rents/selectbuilding' => 'rents#selectbuildingrent', :as => :selectbuildingrent
  get 'photos/selectbuilding' => 'photos#selectbuildingphoto', :as => :selectbuildingphoto
  get 'floorplans/selectbuilding' => 'floorplans#selectbuildingfloorplan', :as => :selectbuildingfloorplan
  get 'buildings/update_areas' => 'buildings#update_areas', :as => :update_areas
  get 'buildings/update_neighborhoods' => 'buildings#update_neighborhoods', :as => :update_neighborhoods

  resources :reviews
  resources :rents
  resources :floorplans
  resources :photos
  resources :cities

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :buildings do
    resources :reviews
    resources :rents
    resources :floorplans
    resources :photos
  end

  resources :neighborhoods

  match '/terms', to: 'static_pages#terms'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/how-it-works', to: 'static_pages#how'
  match '/careers', to: 'static_pages#careers'
  match '/press', to: 'static_pages#press'
  match '/partners', to: 'static_pages#partners'
  match '/privacy', to: 'static_pages#privacy'
  match '/advertise', to: 'static_pages#advertise'
  match '/managers', to: 'static_pages#managers'
  match '/guidelines', to: 'static_pages#guidelines'
  match '/abuse', to: 'static_pages#abuse'
  match '/allcities', to: 'static_pages#allcities'

  match '/signup', to: 'users#sign_up'
  match '/signin', to: 'sessions#sign_in'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/building.rb
class Building < ActiveRecord::Base
  attr_accessible :name, :address, :city, 
  :latitude, :longitude, :area, :neighborhood, :website, :zip, 
  :management, :city_id, :area_id, :neighborhood_id, :slug, :status, :user_id, :gmaps, :nickname, :reviews_count

  has_many :reviews, dependent: :destroy
  has_many :rents, dependent: :destroy
  has_many :photos, dependent: :destroy
  has_many :floorplans, dependent: :destroy

  belongs_to :city
  belongs_to :area
  belongs_to :neighborhood
  belongs_to :user

  validates :name, 				        presence: true
  validates :zip, 				        presence: true, zip: true 
  validates :address, 			      presence: true, uniqueness: true
  # validates :latitude, 				  allow_blank: true, numericality: true, uniqueness: true
  # validates :longitude, 				allow_blank: true, numericality: true, uniqueness: true
  # validates :management, 		    allow_blank: true
  validates :city_id,		          presence: true, numericality: { only_integer: true }
  #validates :area_id,             presence: true, numericality: { only_integer: true }
  #validates :neighborhood_id,	    presence: true, numericality: { only_integer: true }

  reverse_geocoded_by :latitude, :longitude
  geocoded_by :gmaps4rails_address
  acts_as_gmappable :process_geocoding => false

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  scope :has_reviews, joins{reviews.outer}.where{reviews.id != nil}
  scope :has_image, includes{photos}.where{photos.id != nil}

  def self.search_attributes(search) # Used on the home page and search header search field to search all buildings by any of its attributes
    city_search = self.joins{city}.where{(zip =~ "%#{search}%") | (name =~ "%#{search}%") | (address =~ "%#{search}%") | (nickname =~ "%#{search}%") | (city.name =~ "%#{search}%")}
    hood_search = self.joins{neighborhood}.where{ neighborhood.name =~ "%#{search}%" }
    area_search = self.joins{area}.where{ area.name =~ "%#{search}%" }
    return city_search + hood_search + area_search
  end

  def gmaps4rails_address # Gets a building's address for creating the latitude & longitude
    "#{self.address}, #{self.zip}"
  end

  def self.star_avg_image(rating)
      self.reviews.average_review_rating(rating)
  end

  def average_review_rating(rating)
    return nil if self.blank?
    self.average(rating)
  end

  def average_overall
    instance_eval { reduce(:+) / size.to_f }
  end

  def self.search_by_city(search) # Used for the individual city views to find all the buildings in a city
    self.joins{city}.where{city.name =~ "%#{search.name}%"}
  end

  def self.select_only_in_city(selection) # Used for the individual city pages to get buildings only in that city
    self.joins{city}.where{city.name =~ selection}
  end

  def find_for_count(name)
    self.select { |place| place.name == name }
  end

  def self.sort_by_reviews(array, type) # For the building results page and lets users filter results by the number of reviews for a building or the building's overall average rating
    if type == "count"
      array.sort! { |x, y| y.reviews.count <=> x.reviews.count }
    else
      array.sort! { |x, y| y.reviews.average("overall").to_f <=> x.reviews.average("overall").to_f }
    end
  end

  def self.delete_current_building(building)
    self.all.delete_if { |x| x.name == building.name }
  end

  def self.get_best_buildings(number)
    sorted = self.uniq
    sorted = sorted.sort { |x, y| y.reviews.average("overall").to_f <=> x.reviews.average("overall").to_f }
    sorted.first(number)
  end

  def self.get_worst_buildings(number)
    sorted = self.uniq
    sorted = sorted.sort { |x, y| x.reviews.average("overall").to_f <=> y.reviews.average("overall").to_f }
    sorted.first(number)
  end

  def self.select_featured(many) #randoly selects from the passed in array. Used for the home page featured buildings
    self.order("RANDOM()").first(many)
  end

  private

  def downcase_name
    self.name = self.name.downcase if self.name.present?
  end

  def downcase_address
    self.address = self.address.downcase if self.address.present?
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

	def new
		if user_signed_in?
			@building = Building.new
		else
	  		redirect_to new_user_session_path
    	end
	end

	def create
		@building = Building.new(params[:building])
		if @building.save
			flash[:notice] = "Successfully created building."
			current_user.buildings << @building
			redirect_to building_path(@building)
		else
			render :action => 'new'
		end
	end

	def show
		@building = Building.find(params[:id])
		redirect_to building_reviews_path(@building)
		if request.path != building_path(@building)
			redirect_to @building, status: :moved_permanently
		end
	end

	def index
		empty_search = params[:search] ? false : true

    	if empty_search
    		@buildings = []
    		@buildingresults = Kaminari.paginate_array(@buildings).page(params[:page]).per(10)
    		@json = @buildings.to_gmaps4rails
    		@areas = @buildings.map(&:area)
  			@neighborhoods = @buildings.map(&:neighborhood)
    	else
	  		@search = Building.search_attributes(params[:search])
	  		@buildings = Building.sort_by_reviews(@search, "count")
	  		@buildingresults = Kaminari.paginate_array(@buildings).page(params[:page]).per(10)
  			@areas = @buildings.map(&:area)
  			@neighborhoods = @buildings.map(&:neighborhood)
  			@json = @buildingresults.to_gmaps4rails do |building, marker|
			  	marker.infowindow render_to_string(:partial => "/buildings/infowindow", :locals => { :building => building})
			    marker.title "#{building.name}"
			end
	  	end
	end

	def update

	end

	def edit
		@building = Building.find(params[:id])
	end

	def destroy

	end

	def update_areas
	   city_id =  (params[:city_id].nil? || params[:city_id].empty?) ? 0 : params[:city_id].to_i
       # updates artists and songs based on genre selected
       if city_id == 0
         @areas = []
         @neighborhoods = []
        
        else
          city = City.find(params[:city_id])
          # map to name and id for use in our options_for_select
          @areas = city.areas.map{|a| [a.name, a.id]}
          @neighborhoods = Neighborhood.where(:area_id => city.areas.each{|a| a.id}).map{|s| [s.name, s.id]}
      end
      @areas.insert(0, "Select an Area")
      @neighborhoods.insert(0, "Select a neighborhood") 
      @areas = city.areas.order("name asc").map{|a| [a.name, a.id]}
	  @neighborhoods = Neighborhood.where(:area_id => city.areas.each{|a| a.id}).order("name asc").map{|s| [s.name, s.id]}
  	end
 
  	def update_neighborhoods
	    # updates songs based on artist selected
	    area = Area.find(params[:area_id])
  		@neighborhoods = area.neighborhoods.sort_by(&:name).map{|s| [s.name, s.id]}.insert(0, "Select a neighborhood")
  	end

end

app/helpers/buildings_helper.rb
module BuildingsHelper
	

	def first_n_words_of_first_review(building, n)
		"#{building.reviews.map(&:pros).first.split(/\s+/, n+1)[0...n].join(' ')}..."
	end


	def share_icons
		raw("
			<div class=\"addthis_toolbox addthis_default_style\">
			<a class=\"addthis_button_preferred_1\"></a>
			<a class=\"addthis_button_preferred_2\"></a>
			<a class=\"addthis_button_preferred_3\"></a>
			<a class=\"addthis_button_preferred_4\"></a>
			<a class=\"addthis_button_compact\"></a>
			<a class=\"addthis_counter addthis_bubble_style\"></a>
			</div>
			<script type=\"text/javascript\">var addthis_config = {\"data_track_addressbar\":true};</script>
			<script type=\"text/javascript\" src=\"//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51a3e5fd46cf9524\"></script>")
	end

end

app/views/buildings/_building_header.html.erb
<div class="building-topbar">
	<div class="building-info">
		<h1><%= @building.name %></h1>
		<p id="geography"><%= geogrify(@building) %></p>
		<p id="address-text"><%= @building.address %>, <%= @building.zip %></p>

		<div class="review-rent-btns"><!-- Write review & submit rent btns in bldg prof -->
			<%= link_to(raw("<button class=\"btn btn-small\">Add Photo</button>"), new_building_photo_path(@building)) %>
			<%= link_to(raw("<button class=\"btn btn-small\">Add Rent</button>"), new_building_rent_path(@building)) %>
			<%= link_to(raw("<button class=\"btn btn-small\">Write Review</button>"), new_building_review_path(@building)) %>
		</div>

		<div class="building-stats">
			<%= render 'buildings/star_ratings' %>
		</div>
	</div>
	
	<div class="photos-area">
		<ul id="gallery">
		<% if @building.photos.blank? %>
			<li><%= image_tag 'nobuildingimage.png' %></li>
		<% else %>					
			<% @building.photos.each do |photo| %>
				<li><%= image_tag photo.image.url %></li>
			<% end %>
		<% end %>	
		</ul>
	</div>
</div>

app/views/buildings/_buildingresults.html.erb
<% if @buildingresults.nil? || @buildingresults.empty?  %>
	<%= render 'noresults' %>
	<% else %>
<div class="pagination">
	<%= paginate @buildingresults %>
</div>

<ul class="building-results-ul"> 
	<% @buildingresults.each do |building| %>

		<%= link_to building do %>
			<li class="building-listing">

				<div class="building-image">
					<!-- Sets default image if building does not have one yet -->
					<% if building.photos.blank? %>
						<%= image_tag 'nobuildingimage.png', size: "100x100" %>
					<% else %>
						<%= image_tag building.photos.first.image.url, size: "100x100" %>
					<% end %>
				</div>
				<!-- All the content to the right of the building image -->
				<div class="building-listing-info">
					<div>
						<h3><%= building.name%></h3>

						<!-- Shows the overall average star image -->
						<% if building.reviews.nil? || building.reviews.blank? %>
							<img src="/assets/stars/star0.png" height="16px" width="80px">
						<% else %>
						<%= star_image((building.reviews.average("overall")*4).round) %>
						<% end %>
						<!-- Shows reviews count next to star -->
						<% if building.reviews.blank? %>
							<p id="reviews-count">No reviews yet</p>		
						<% else %>
							<p id="reviews-count">(<%= raw("#{building.reviews.count}") %> Reviews)</p>
						<% end %>

					</div>
					<h4>
					<%= geogrify(building) %>
					</h4>
					<span><%= building.address %>, <%= building.zip %></span>
					
						<% if building.reviews.blank? %>
							<br>					
							<%= link_to(raw("<button class=\"btn btn-small\">Submit a Rent</button>"), new_building_rent_path(building)) %>
							<%= link_to raw("<button class=\"btn btn-small\">Write the first review</button>"), new_building_review_path(building) %>
						<% else %>
							<p>
								<%= first_n_words_of_first_review(building, 11) %>
							</p>
						<% end %>

				</div>
							
			</li>
		<% end %>
	<% end %>
</ul>
<div class="pagination">
<%= paginate @buildingresults %>
</div>
<% end %>

app/views/buildings/_infowindow.html.erb
<div class="info-window">
	   <% if building.reviews.nil? || building.reviews.blank? %>
			<img src="/assets/stars/star0.png" height="16px" width="80px">
		<% else %>
		<%= star_image((building.reviews.average("overall")*4).round) %>
		<% end %>
		
	   <h1><%= link_to building.name, building %></h1>
	   <h2>Address: <%= building.address %></h2>
	</div>
</div>

app/views/buildings/_newbuildingform.html.erb
<div class="new-building-form">
	<h1>Your addition will help other renters - thank you!</h1>
	<%= render 'newbuildingsfields' %>

</div>

<div class="new-building-sidebar">
	<h2>&nbsp;Adding a building:&nbsp;</h2>
	<p>Our number one priority is ensuring the accuracy and objectivity of our review and building data</p>
	
	<p>We review each submission and will research any information we feel may be fraudulent or inaccurate and take the appropriate action</p>
</div>	

app/views/buildings/_newbuildingsfields.html.erb
<%= form_for @building, validate: true do |f| %>

<div class="building-form-fields">

	<div id="building-name">
		<p>Building name:</p>
		<%= f.text_field :name,
			placeholder: "Name or address", style: "width: 100%;" %>
		<br />
	</div>

	<div id="address-field">
		<p>Street address:</p>
		<%= f.text_field :address,
			placeholder: "Full street address", style: "width: 100%;" %>
		<br />
	</div>

	<div id="zip">
		<p>Zip code:</p>
		<%= f.text_field :zip, 
			style: "width: 100%;", 
			placeholder: "Zip code" %>
		<br />
	</div>

	<div id="city">
		<p>City:</p>
		<%= f.collection_select(:city_id, City.order('name ASC'),  :id, :name_with_state, {:prompt   => "Select a City"}, {:id => 'cities_select'}) %>
		<br />
	</div>

	<div id="area">
		<p>City area (optional):</p>
		<%= f.collection_select(:area_id, [], :id, :name, {:prompt   => "Select an Area"}, {:id => 'areas_select'}) %>
		<br />
	</div>

	<div id="neighborhood">
		<p>Neighborhood (optional):</p>
		<%= f.collection_select(:neighborhood_id, [], :id, :name, {:prompt   => "Select a Neighborhood"}, {:id => 'neighborhoods_select'}) %>
		<br />
	</div>

	<div id="management">
		<p>Management/Landlord (optional):</p>
		<%= f.text_field :management,
			placeholder: "Management company or landlord", 
			style: "width: 96%;" %>
		<br />
	</div>

</div>

	<div id="create-building-btn">
	<%= f.submit 'Create building', class: "btn btn-primary btn-large" %>
	</div>

<% end %>

app/views/buildings/_no_nearby.html.erb
<div class="no-nearby">
	<h3>It looks like there are no buildings within a half mile of this one</h3>
</div>

app/views/buildings/_noresults.html.erb
<div class="no-results">

<h3>Here are a few reasons why:</h3>
<ul>
	<li><p>If you are looking for a specific building, we may not have it in our database yet. You can add a new building <%= link_to "here", new_building_path %></p></li>
	<li><p>If you tried a city, zip code, area, or neighborhood, we may not have any buildings in the geographic area you searched for. You can add a new building <%= link_to "here", new_building_path %></p></li>
	<li><p>There may be multiple instances for the city/area/neighborhood you searched for - try a different attribute like a zip code or street name</p></li>
	<li><p>If you searched by address, try searching without abbreviations (ie, "Drive instead of "Dr")</p></li>
	<li><p>If you are searching by zip code, please use just the five-character base zip code (ie, 60601 instead of 60601-4722)</p></li>
</ul>
</div>

app/views/buildings/_refine_search.html.erb
<h3>Refine your search</h3>
<%= form_tag buildings_path, method: :get do %>
	<%= select_tag :reviews, "<option value=\"count\">Number of Reviews</option><option value=\"overall\">Average Overall Rating</option>".html_safe, :onchange => "this.form.submit();" %>
<% end %>

<% if @areas.blank? || @areas.nil? %>

	<% @areas.group_by(&:name).each do |name, area| %>
		<p><%= area.name %></p>
		<p><%= area.count %></p>
	<% end %>
<% end %>

<% @neighborhoods.group_by(&:name).each do |name, neighborhood| %>
  <p><%= name %></p>
  <p><%= neighborhood.count %></p>
<% end %>

app/views/buildings/_star_ratings.html.erb
<div id="overall-rating-div">
	<ul>
		<li>
			<h4><span>Overall Rating:</span></h4>
		</li>
		<li id="overall-avg-stars">
			<% if @reviews.average_review_rating("overall").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("overall")*4).round) %>
			<% end %>
		</li>
	</ul>
</div>
<div class="stats-labels">
	<ul>
		<li>
			<h4>Management Rating:</h4>
		</li>
		<li>
			<h4>Staff Rating:</h4>
		</li>
		<li>
			<h4>Maintenance Rating:</h4>
		</li>
		<li>
			<h4>Amenities Rating:</h4>
		</li>
		<li>
			<h4>Neighborhood Rating:</h4>
		</li>
		<li>
			<h4>Safety Rating:</h4>
		</li>
		<li>
			<h4>Noise Rating:</h4>
		</li>
		<li>
			<h4>Transporation Rating:</h4>
		</li>
	</ul>
</div>
<div class="stats-stars">
	<ul>
		<li>
			<% if @reviews.average_review_rating("management_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("management_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("staff_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("staff_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("maintenance_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("maintenance_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("amenities_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("amenities_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("neighborhood_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("neighborhood_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("safety_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("safety_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("noise_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("noise_rating")*4).round) %>
			<% end %>
		</li>
		<li>
			<% if @reviews.average_review_rating("transportation_rating").nil? %>
				<%= star_image(0) %>
			<% else %>
				<%= star_image((@reviews.average("transportation_rating")*4).round) %>
			<% end %>
		</li>
	</ul>
</div>

app/views/buildings/_thanks.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'buildings' %>
<% end %>

<% provide(:title, "Thank you for your submission") %>

<div class="em-buffer-3"></div>

<div class="container">
	<div class="main-content-area">

		<div class="thankyou-hero">
			<h1>Thank you for submitting a new building!</h1>
			<h2>We will review your submission and send you a notification once your building is approved</h2>
			<%= @building %>
			<div>
			</div>
		</div>

		<div class="thankyou-fb-box">
			<h2>In the meantime, you can like us on Facebook or follow us on Twitter!</h2>
		</div>

		<div>
		</div>

	</div>
</div>

app/views/buildings/index.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'buildings' %>
	<%= stylesheet_link_tag 'gmaps4rails' %>
<% end %>

<% provide(:title, 'Search buildings') %>
<%= render 'layouts/gmaps_autozoom' %>

<div class="bg-texture-wrapper">
	<div class="container">
		<div class="em-buffer-3"></div>

		<div class="search-sidebar">
			<div class="map-area">
				<%= gmaps({
  				"map_options" => {"auto_zoom" => true },
 				"markers" => {"data" => @json }
				}) %>
			</div>
			<div class="search-options">
				
			</div>
		</div>

		<div class="building-results">
			
			<div class="results-header">
			<% if @buildingresults.nil? || @buildingresults.empty? %>
				<h2>Your search did not return any results</h2>
			<% else %>
				<h2>Your search returned <%= pluralize(@buildings.count, "result") %></h2>
			<% end %>
			<%= link_to "Add building", new_building_path %>
			</div>

			<%= render 'buildingresults' %>
		</div>
		<div class="buffer"></div>
	</div>
</div>

app/views/buildings/new.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'buildings' %>
<% end %>

<% content_for :scripts do %>
  <%= javascript_include_tag "static_helpers" %>
<% end %>

<% provide(:title, 'Create a new building') %>

<div class="bg-texture-wrapper">
  <div class="container">
    <div class="center-div">
      <% if @product && !@product.new_record %>
        <%= render 'thanks' %>
      <% else %>
        <%= render 'newbuildingform' %>
      <% end %>
    </div>
  </div>
</div>


<script>
  $(document).ready(function() {
    $('#cities_select').change(function() {
      $.ajax({
        url: "<%= update_areas_path %>",
        data: {
          city_id : $('#cities_select').val()
        },
        dataType: "script"
      });
    });
    $('#areas_select').change(function() {
      $.ajax({
        url: "<%= update_neighborhoods_path %>",
        data: {
          area_id : $('#areas_select').val()
        },
        dataType: "script"
      });
    });
  });
</script>

app/views/buildings/update_areas.js.erb
$('#areas_select').html("<%= escape_javascript(options_for_select(@areas)) %>");
$('#neighborhoods_select').html("<%= escape_javascript(options_for_select(@neighborhoods)) %>");

app/views/buildings/update_neighborhoods.js.erb
$('#neighborhoods_select').html("<%= escape_javascript(options_for_select(@neighborhoods)) %>");