config/routes.rb
Breezedigs::Application.routes.draw do

  root to: 'static_pages#home'

  match "/sitemap.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3
  match "/sitemapa.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  ActiveAdmin.routes(self)

  resources :users do
    collection do
      get :manager
      get :tenant
    end
  end

  get 'reviews/selectbuilding' => 'reviews#selectbuilding', :as => :selectbuilding
  get 'rents/selectbuilding' => 'rents#selectbuildingrent', :as => :selectbuildingrent
  get 'photos/selectbuilding' => 'photos#selectbuildingphoto', :as => :selectbuildingphoto
  get 'floorplans/selectbuilding' => 'floorplans#selectbuildingfloorplan', :as => :selectbuildingfloorplan
  get 'buildings/update_areas' => 'buildings#update_areas', :as => :update_areas
  get 'buildings/update_neighborhoods' => 'buildings#update_neighborhoods', :as => :update_neighborhoods

  resources :reviews
  resources :rents
  resources :floorplans
  resources :photos
  resources :cities

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :buildings do
    resources :reviews
    resources :rents
    resources :floorplans
    resources :photos
  end

  resources :neighborhoods

  match '/terms', to: 'static_pages#terms'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/how-it-works', to: 'static_pages#how'
  match '/careers', to: 'static_pages#careers'
  match '/press', to: 'static_pages#press'
  match '/partners', to: 'static_pages#partners'
  match '/privacy', to: 'static_pages#privacy'
  match '/advertise', to: 'static_pages#advertise'
  match '/managers', to: 'static_pages#managers'
  match '/guidelines', to: 'static_pages#guidelines'
  match '/abuse', to: 'static_pages#abuse'
  match '/allcities', to: 'static_pages#allcities'

  match '/signup', to: 'users#sign_up'
  match '/signin', to: 'sessions#sign_in'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
		@building = Building.find(params[:building_id])
		@reviews = @building.reviews
		@json = @building.to_gmaps4rails
		@nearby = Building.near(@building, 0.5).delete_current_building(@building).first(5)
	end

	def new
		no_building = params[:building_id] ? false : true
		if no_building
			redirect_to selectbuilding_path
		else
			if user_signed_in?
				@building = Building.find(params[:building_id])
				@review = @building.reviews.new
			else
		  		redirect_to new_user_session_path
	    	end
		end
	end

	def create
		@building = Building.find(params[:building_id])
		@review = @building.reviews.new(params[:review])
		if @review.save!
			flash[:notice] = "Thank you for submitting a review and contributing to our community!"
			current_user.reviews << @review
			redirect_to building_path(@building)
		else
			render :action => 'new'
		end
	end

	def show
	end

	def update
		@review = Review.find(params[:id])
		if @review.update_attributes(params[:review])
			redirect_to current_user
		else
			render :action => 'edit'
		end
	end

	def edit
		@review = Review.find(params[:id])
		@building = @review.building
	end

	def destroy
		@review = Review.find(params[:id])
		@review.delete
		redirect_to current_user
	end

	def setup_building
		@building = Building.find(params[:building_id])
	end

	def selectbuilding
		@featured = Building.select_only_in_city("Chicago").has_image.select_featured(15)
	end
	
end

app/helpers/reviews_helper.rb
module ReviewsHelper
	def star_ratings(rating)
      raw("
		<input name=\"review[#{rating}]\" type=\"radio\" class=\"star\" value=\"1\"/>
		<input name=\"review[#{rating}]\" type=\"radio\" class=\"star\" value=\"2\"/>
		<input name=\"review[#{rating}]\" type=\"radio\" class=\"star\" value=\"3\"/>
		<input name=\"review[#{rating}]\" type=\"radio\" class=\"star\" value=\"4\"/>
		<input name=\"review[#{rating}]\" type=\"radio\" class=\"star\" value=\"5\"/>")
	end

	def sort_recent(reviews)
	  reviews.sort_by { |obj| obj.created_at }
	end

end

app/views/reviews/_newreviewfields.html.erb
<%= form_for([@building, @building.reviews.new], validate: true) do |f| %>
 	
<div class="review-form-fields">

	<h4>What is your overall rating of living here?*</h4>
	<%= star_ratings("overall") %>
	<br><br>
	<div>
		<p>Pros*: <span id="fw-400"><i>(75 character minimum)</i></span></p>
		<%= f.text_area :pros,
			placeholder: "General positives about living in this building", size: "5x3" %>
		<br />
	</div>

	<div>
		<p>Cons*: <span id="fw-400"><i>(75 character minimum)</i></span></p>
		<%= f.text_area :cons,
			placeholder: "Negative aspects of living in this building", size: "5x3" %>
		<br />
	</div>

	<div>
		<p>When did you live here?* <span id="fw-300"><i>(Leave end date unchanged if you currently live here)</i></span></p>
		<!-- &nbsp;&nbsp;<i class="icon-info-sign"></i><br> -->
			<div id="start-stop">
			<%= select_year Date.today, start_year: Time.now.year, end_year: Time.now.year - 95, field_name: :start, prefix: :review %>
			<p>&nbsp;&nbsp;to&nbsp;&nbsp;</p>
			<%= select_year Date.today, start_year: Time.now.year, end_year: Time.now.year - 95, field_name: :stop, prefix: :review %>
			</div>
	</div>		

	<div class="tell-us-more"><h5>Can you tell us a bit more?(optional)</h5></div><br>

	<div id="advice">
		<p>Advice:</p>
		<%= f.text_area :advice,
			placeholder: "Advice to prospective tenants about living in this building", size: "5x2" %>
		<br />
	</div>

	<div id="msm">
		<p>Management & Staff <span class="fw-300">(optional)</span></p>
		<%= f.text_area :msm,
			placeholder: "Responsiveness & practices of management, friendliness of staff, maintenance & upkeep, etc.", size: "5x5" %>
		<br />
	</div>

	<div id="nsn">
		<p>Neighborhood, Safety, Noise <span class="fw-300">(optional)</span></p>
		<%= f.text_area :nsn,
			placeholder: "What the neighborhood is like, are there any safety concerns/issues, is the area particularly noisy, etc.", size: "5x5" %>
		<br />
	</div>

	<div id="unitamen">
		<p>Amenities & Unit Quality <span class="fw-300">(optional)</span></p>
		<%= f.text_area :unitamen,
			placeholder: "Noteworthy amenities & the quality of the units", size: "5x5" %>
		<br />
	</div>

	<div id="transpark">
		<p>Transportation & Parking <span class="fw-300">(optional)</span></p>
		<%= f.text_area :parktrans,
			placeholder: "Access to transportation & availability of parking", size: "5x5" %>
	</div>

	<div class="tell-us-more"><h5>Can you rate a few more things?(optional)</h5></div><br>

	<div class="star-rtngs">
	<p>Management Rating:</p>
	<%= star_ratings("management_rating") %>

	<br><p>Staff Rating:</p>
	<%= star_ratings("staff_rating") %>

	<br><p>Maintenance Rating:</p>
	<%= star_ratings("maintenance_rating") %>

	<br><p>Amenities Rating:</p>
	<%= star_ratings("amenities_rating") %>
	</div>

	<div class="star-rtngs">
	<p>Neighborhood Rating:</p>
	<%= star_ratings("neighborhood_rating") %>

	<br><p>Noise Rating:</p>
	<%= star_ratings("noise_rating") %>

	<br><p>Safety Rating:</p>
	<%= star_ratings("safety_rating") %>

	<br><p>Transportation Rating:</p>
	<%= star_ratings("transportation_rating") %>
	</div>

</div>	

	<div id="create-review-btn">
	<%= f.submit 'Submit Review', class: "btn btn-primary btn-large" %>
	</div>

<% end %>

app/views/reviews/_noreviews.html.erb
<%= render 'layouts/facebooklikebox' %>

<div class="no-reviews">
<h2>We do not have any reviews for this building yet</h2>
<p>If you have lived at this building, we'd appreciate it if you would write a review to let other renters know about your experience.</p>
<p>If not, you can help us grow and get more reviews by sharing our site:</p>
<br><br>
<div class="fb-like-box" data-href="https://www.facebook.com/breezedigs" data-width="500px" data-show-faces="true" data-stream="false" data-show-border="false" data-header="false"></div>
</div>

app/views/reviews/_selectbuildingresults.html.erb
<ul> 
	<% @buildings.each do |building| %>

		<%= link_to new_building_review_path(building) do %>
			<li class="select-bldg-listing">

				<div class="bldg-listing-info">
					<h1><%= building.name%></h1>
					<h2>
					<%= geogrify(building) %>: <span><%= building.address %> - <%= building.zip %></span>
					</h2>
				</div>
					
			<button class="select-bldg-btn">Review</button>
							
			</li>
		<% end %>
	<% end %>
</ul>
<div class="pagination"><%= paginate @buildings %></div>

app/views/reviews/edit.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'reviews' %>
<% end %>

<% provide(:title, "Edit Review") %>

<div class="bg-texture-wrapper">
	<div class="container">
		<div class="new-review-form">
			<h1>Your review will help other renters - thank you!</h1>
			<div class="building-profile-new">
				<div class="building-text">
					<h2><%= link_to @building.name, building_path(@building) %></h1>
					<p id="geography"><%= building_geography %></p>
					<p id="address-text"><%= @building.address %>, <%= @building.zip %></p>
				</div>
			</div>
			<%= form_for(@review, validate: true) do |f| %>
					<div class="review-form-fields">

						<h4>What is your overall rating of living here?</h4>
						<% (1...@review.overall).each do %>
							<input name="review[overall]" type="radio" class="star" value="1">
						<% end %>
						<input name="review[overall]" type="radio" class="star" value="1" checked="checked">
						<% (5-@review.overall).times do %>
							<input name="review[overall]" type="radio" class="star" value="1">
						<% end %>

						<br>
						<div>
							<p>Pros:</p>
							<%= f.text_area :pros,
								placeholder: "General positives about living in this building", size: "5x3" %>
							<br />
						</div>

						<div>
							<p>Cons:</p>
							<%= f.text_area :cons,
								placeholder: "Negative aspects of living in this building", size: "5x3" %>
							<br />
						</div>

						<div class="tell-us-more"><h5>Can you tell us a bit more?(optional)</h5></div><br>

						<div id="advice">
							<p>Advice:</p>
							<%= f.text_area :advice,
								placeholder: "Advice to prospective tenants about living in this building", size: "5x2" %>
							<br />
						</div>

						<div id="msm">
							<p>Management & Staff <span class="fw-300">(optional)</span></p>
							<%= f.text_area :msm,
								placeholder: "Responsiveness & practices of management, friendliness of staff, maintenance & upkeep, etc.", size: "5x5" %>
							<br />
						</div>

						<div id="nsn">
							<p>Neighborhood, Safety, Noise <span class="fw-300">(optional)</span></p>
							<%= f.text_area :nsn,
								placeholder: "What the neighborhood is like, are there any safety concerns/issues, is the area particularly noisy, etc.", size: "5x5" %>
							<br />
						</div>

						<div id="unitamen">
							<p>Amenities & Unit Quality <span class="fw-300">(optional)</span></p>
							<%= f.text_area :unitamen,
								placeholder: "Noteworthy amenities & the quality of the units", size: "5x5" %>
							<br />
						</div>

						<div id="transpark">
							<p>Transportation & Parking <span class="fw-300">(optional)</span></p>
							<%= f.text_area :parktrans,
								placeholder: "Access to transportation & availability of parking", size: "5x5" %>
						</div>

						<div class="tell-us-more"><h5>Can you rate a few more things?(optional)</h5></div><br>

						<div class="star-rtngs">
						<p>Management Rating:</p>
						<% if @review.management_rating.blank? %>
							<%= star_ratings("management_rating") %>
						<% else %>
							<% (1...@review.management_rating).each do %>
								<input name="review[management_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[management_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.management_rating).times do %>
								<input name="review[management_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>

						<br><p>Staff Rating:</p>
						<% if @review.staff_rating.blank? %>
							<%= star_ratings("staff_rating") %>
						<% else %>
							<% (1...@review.staff_rating).each do %>
								<input name="review[staff_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[staff_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.staff_rating).times do %>
								<input name="review[staff_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>

						<br><p>Maintenance Rating:</p>
						<% if @review.maintenance_rating.blank? %>
							<%= star_ratings("maintenance_rating") %>
						<% else %>
							<% (1...@review.maintenance_rating).each do %>
								<input name="review[maintenance_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[maintenance_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.maintenance_rating).times do %>
								<input name="review[maintenance_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>						

						<br><p>Amenities Rating:</p>
						<% if @review.amenities_rating.blank? %>
							<%= star_ratings("amenities_rating") %>
						<% else %>
							<% (1...@review.amenities_rating).each do %>
								<input name="review[amenities_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[amenities_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.amenities_rating).times do %>
								<input name="review[amenities_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>
						</div>

						<div class="star-rtngs">
						<p>Neighborhood Rating:</p>
						<% if @review.neighborhood_rating.blank? %>
							<%= star_ratings("neighborhood_rating") %>
						<% else %>
							<% (1...@review.neighborhood_rating).each do %>
								<input name="review[neighborhood_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[neighborhood_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.neighborhood_rating).times do %>
								<input name="review[neighborhood_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>

						<br><p>Noise Rating:</p>
						<% if @review.noise_rating.blank? %>
							<%= star_ratings("noise_rating") %>
						<% else %>
							<% (1...@review.noise_rating).each do %>
								<input name="review[noise_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[noise_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.noise_rating).times do %>
								<input name="review[noise_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>

						<br><p>Safety Rating:</p>
						<% if @review.safety_rating.blank? %>
							<%= star_ratings("safety_rating") %>
						<% else %>
							<% (1...@review.safety_rating).each do %>
								<input name="review[safety_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[safety_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.safety_rating).times do %>
								<input name="review[safety_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>

						<br><p>Transportation Rating:</p>
						<% if @review.transportation_rating.blank? %>
							<%= star_ratings("transportation_rating") %>
						<% else %>
							<% (1...@review.transportation_rating).each do %>
								<input name="review[transportation_rating]" type="radio" class="star" value="1">
							<% end %>
							<input name="review[transportation_rating]" type="radio" class="star" value="1" checked="checked">
							<% (5-@review.transportation_rating).times do %>
								<input name="review[transportation_rating]" type="radio" class="star" value="1">
							<% end %>
						<% end %>
						</div>

					</div>	

						<div id="create-review-btn">
						<%= f.submit 'Update Review', class: "btn btn-primary btn-large" %>
						</div>

					<% end %>
					</div>

					<div class="new-review-sidebar">
						<h2>&nbsp;To our community:&nbsp;</h2>
						<p>Our number one priority is ensuring the accuracy and objectivity of our review and building data</p>
						
						<p>We review each submission before approving them to be used and will research any information we feel may be fraudulent or inaccurate and take the appropriate action</p>

						<br>
						<p id="bold">Things that we will not allow in reviews:</p>

						<br>
						<ul>
							<li>Rants, venting, or obscenities</li>
							<li>Personal insults or defamatory attacks (by name, title, or association)</li>
							<li>Aggressive or discriminatory language</li>
							<li>Content not relevant or helpful to other renters</li>
							<li>Text in ALL CAPS or using excessively poor grammar</li>
						</ul>
					</div>	
	</div>
</div>	

app/views/reviews/index.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'buildings' %>
	<%= stylesheet_link_tag 'reviews' %>
<% end %>

<% content_for :scripts do %>
	<%= javascript_include_tag "reviews" %>
	<%= javascript_include_tag "buildings" %>
<% end %>

<% provide(:title, @building.name) %>

<div class="bg-texture-wrapper">
	<div class="container">
		<div class="building-profile">
			<% flash.each do |key, value| %>
			<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>

			<div class="building-content-area">
			<%= render 'buildings/building_header' %>

			<div class="building-data-toggle"><!-- To switch between reviews and rental data -->
				<%= link_to "<button class=\"toggle tselect\">Reviews</button>".html_safe, building_reviews_path(@building) %>
				<%= link_to "<button class=\"toggle\">Rental Data</button>".html_safe, building_rents_path %>
			</div>

				<div class="reviews">
					<div class="review-header">
						<h2><%= pluralize(@reviews.count,'review') %> for this building</h2>
					</div>

					<div class="review-content">
						<% if @reviews.nil? || @reviews.blank? %>
							<%= render 'noreviews' %>
						<% else %>
							<% sort_recent(@reviews).each do |review| %>
							<div class="single-review-header">
								<div>									
									<h4>Overall rating:</h4>
									<%= star_image((review[:overall]*4).round) %>
									<p>
										Posted by: 
										<% if review.user.nil? || review.user.first_name.blank? %>
										Anonymous
										<% else %>
										<%= review.user.first_name.capitalize %> 
										<%= review.user.last_name[0,1].capitalize %>
										<% end %>
										. on <%= review.created_at.strftime("%d %b. %Y") %>
									</p>
								</div>
								<div>

								</div>
							</div>
							<div class="review">
								<div class="other-review-ratings">
									<div class="other-stats-labels">
										<ul>
											<li>
												<h4>Management Rating:</h4>
											</li>
											<li>
												<h4>Staff Rating:</h4>
											</li>
											<li>
												<h4>Maintenance Rating:</h4>
											</li>
											<li>
												<h4>Amenities Rating:</h4>
											</li>
											<li>
												<h4>Neighborhood Rating:</h4>
											</li>
											<li>
												<h4>Safety Rating:</h4>
											</li>
											<li>
												<h4>Noise Rating:</h4>
											</li>
											<li>
												<h4>Transporation Rating:</h4>
											</li>
										</ul>
									</div>
									<div class="review-other-stars">
										<ul>
											<li>
												<% if review[:management_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:management_rating]*4).round) %>
												<% end %>
											</li>
											<li>
												<% if review[:staff_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:staff_rating]*4).round) %>
												<% end %>	
											</li>
											<li>
												<% if review[:maintenance_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:maintenance_rating]*4).round) %>
												<% end %>
											</li>
											<li>
												<% if review[:amenities_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:amenities_rating]*4).round) %>
												<% end %>
											</li>
											<li>
												<% if review[:neighborhood_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:neighborhood_rating]*4).round) %>
												<% end %>
											</li>
											<li>
												<% if review[:safety_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:safety_rating]*4).round) %>
												<% end %>
											</li>
											<li>
												<% if review[:noise_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:noise_rating]*4).round) %>
												<% end %>
											</li>
											<li>
												<% if review[:transportation_rating].nil? %>
													<p>N/A</p>
												<% else %>
													<%= light_star_image((review[:transportation_rating]*4).round) %>
												<% end %>
											</li>
										</ul>
									</div>
								</div>
								<div class="review-text">
								<!-- Pros & Cons always required so no need to have conditional logic -->
								<p><span>Pros -</span> <%= raw("#{review.pros}")%></p>
								<p><span>Cons -</span> <%= raw("#{review.cons}")%></p>
								<!-- Checks if this was filled in & displays nothing if blank -->
								<% if review.msm.blank? %>
								<% else %>								
								<p><span>Management & Staff -</span> <%= raw("#{review.msm}")%></p>
								<% end %>
								<!-- Checks if this was filled in & displays nothing if blank -->
								<% if review.nsn.blank? %>
								<% else %>
								<p><span>Neighborhood, Safety & Noise -</span> <%= raw("#{review.nsn}")%></p>
								<% end %>
								<!-- Checks if this was filled in & displays nothing if blank -->
								<% if review.unitamen.blank? %>
								<% else %>
								<p><span>Amenities & Unit Quality -</span> <%= raw("#{review.unitamen}")%></p>
								<% end %>
								<!-- Checks if this was filled in & displays nothing if blank -->
								<% if review.parktrans.blank? %>
								<% else %>
								<p><span>Parking & Transportation -</span> <%= raw("#{review.parktrans}")%></p>
								<% end %>
								<!-- Checks if this was filled in & displays nothing if blank -->
								<% if review.advice.blank? %>
								<% else %>
								<p><span>Advice -</span> <%= raw("#{review.advice}")%></p>
								<% end %>
								<br><%= share_icons %>
								</div>
							</div>
						<% end %>
					<% end %>
					</div>
				</div>
			</div>
			<%= render 'buildings/building_sidebar' %>
	</div>
</div>
</div>

app/views/reviews/new.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'reviews' %>
<% end %>

<% provide(:title, "Write a new review") %>

<div class="bg-texture-wrapper">
	<div class="container">
		<div class="new-review-form">
			<h1>Your review will help other renters - thank you!</h1>
			<div class="building-profile-new">
				<div class="building-text">
					<h2><%= link_to @building.name, building_path(@building) %></h1>
					<p id="geography"><%= geogrify(@building) %></p>
					<p id="address-text"><%= @building.address %>, <%= @building.zip %></p>
				</div>
			</div>

			<%= render 'newreviewfields' %>

		</div>

		<div class="new-review-sidebar">
			<h2>&nbsp;To our community:&nbsp;</h2>
			<p>Our number one priority is ensuring the accuracy and objectivity of our review and building data</p>
			
			<p>We review each submission before approving them to be used and will research any information we feel may be fraudulent or inaccurate and take the appropriate action</p>

			<br>
			<p id="bold">Things that we will not allow in reviews:</p>

			<br>
			<ul>
				<li><p>Rants, venting, or obscenities</p></li>
				<li><p>Personal insults or defamatory attacks (by name, title, or association)</p></li>
				<li><p>Aggressive or discriminatory language</p></li>
				<li><p>Content not relevant or helpful to other renters</p></li>
				<li><p>Text in ALL CAPS or using excessively poor grammar</p></li>
			</ul>
		</div>
	</div>
</div>	

app/views/reviews/pros.html.erb
pros

app/views/reviews/selectbuilding.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag 'reviews' %>
<% end %>

<% provide(:title, "Select a building") %>

<div class="bg-texture-wrapper">
	<div class="container">
		<div class="main-content-area">
			

			<div class="select-building-box top">
				<h1>Step 1: Select a building to review</h1>
				<%= form_tag buildings_path, method: :get do %>
		 		<p>
		    	<%= text_field_tag :search, params[:search], placeholder: "City, building name, address, zip", class: "select-bldg-search-field"%>

				   	<button type="submit" class="btn btn-primary inline-block top">
		    		Search 
					</button>

				  	</p>
				<% end %>
			</div>

			<div class="select-building-featured">
				<h2>Some suggested buildings</h2>
				<ul class="random-buildings-ul">
				<% @featured.each do |building| %>
					<li class="featured-building">
						<h4><%= building.name %></h4>
						<div class="random-image-container">
							<%= link_to(image_tag(building.photos.first.image.url, width: "120px"), building_path(building)) %>
						</div>
						<% if building.reviews.nil? || building.reviews.blank? %>
							<img src="/assets/stars/star0.png" height="16px" width="80px">
						<% else %>
						<%= star_image((building.reviews.average("overall")*4).round) %>
						<% end %>
					</li>
				<% end %>
				</ul>
			</div>

		</div>
	</div>
</div>