config/routes.rb
Breezedigs::Application.routes.draw do

  root to: 'static_pages#home'

  match "/sitemap.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3
  match "/sitemapa.xml", :controller => "sitemap", :action => "index" # redirects sitemap URL to the one hosted on Amazon S3

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  ActiveAdmin.routes(self)

  resources :users do
    collection do
      get :manager
      get :tenant
    end
  end

  get 'reviews/selectbuilding' => 'reviews#selectbuilding', :as => :selectbuilding
  get 'rents/selectbuilding' => 'rents#selectbuildingrent', :as => :selectbuildingrent
  get 'photos/selectbuilding' => 'photos#selectbuildingphoto', :as => :selectbuildingphoto
  get 'floorplans/selectbuilding' => 'floorplans#selectbuildingfloorplan', :as => :selectbuildingfloorplan
  get 'buildings/update_areas' => 'buildings#update_areas', :as => :update_areas
  get 'buildings/update_neighborhoods' => 'buildings#update_neighborhoods', :as => :update_neighborhoods

  resources :reviews
  resources :rents
  resources :floorplans
  resources :photos
  resources :cities

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :buildings do
    resources :reviews
    resources :rents
    resources :floorplans
    resources :photos
  end

  resources :neighborhoods

  match '/terms', to: 'static_pages#terms'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/how-it-works', to: 'static_pages#how'
  match '/careers', to: 'static_pages#careers'
  match '/press', to: 'static_pages#press'
  match '/partners', to: 'static_pages#partners'
  match '/privacy', to: 'static_pages#privacy'
  match '/advertise', to: 'static_pages#advertise'
  match '/managers', to: 'static_pages#managers'
  match '/guidelines', to: 'static_pages#guidelines'
  match '/abuse', to: 'static_pages#abuse'
  match '/allcities', to: 'static_pages#allcities'

  match '/signup', to: 'users#sign_up'
  match '/signin', to: 'sessions#sign_in'
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/views/layouts/_facebooklikebox.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<footer>
	<div class="footer-narrow">
	<div class="container">
		<div class="upper-footer">
			<h3>View apartments in:</h3>
			<ul class="footer-col no-wrap">
				<%= render 'layouts/footerstaticcities' %>
			</ul>
			<div class="view-all-cities"><%= link_to "View all cities >>", allcities_path %></div>
		</div>
	</div>
</div>
<div class="buffer-small"></div>
		<div class="lower-footer">
			<div class="footer-narrow">
			<div class="container">				
				<ul class="footer-col no-wrap">
					<li>
						<h3 id="footer-title">General</h3>
						<ul>
							<li><%= link_to "Home", root_path %></li>
							<li><%= link_to "Sign Up", new_user_registration_path %></li>
							<li><%= link_to "Sign In", new_user_session_path %></li>
							<li><%= link_to "Write a review", new_review_path %></li>
							<li><%= link_to "Add a building", new_building_path %></li>
						</ul>
					</li>

					<li>
						<h3 id="footer-title">Our Company</h3>
						<ul>
							<li><%= link_to "About Us", about_path %></li>
							<li><%= link_to "Careers", careers_path %></li>
							<li><%= link_to "Contact", contact_path %></li>
						</ul>
					</li>

					<li>
						<h3 id="footer-title">Useful</h3>
						<ul>							
							<li><%= link_to "Advertise", advertise_path %></li>
							<li><%= link_to "Managers", managers_path %></li>
							<li><%= link_to "Partners", partners_path %></li>
						</ul>
					</li>

					<li>
						<h3 id="footer-title">Please Note</h3>
						<ul>
							
							<li><%= link_to "Terms of Use", terms_path %></li>
							<li><%= link_to "Privacy Policy", privacy_path %></li>
							<li><%= link_to "Review Guidelines", guidelines_path %></li>
						</ul>
					</li>

					<li id="social-col">
					<h3 id="footer-title">Social</h3>
						<ul>

							<a href="">
							<li class="social-button facebook" id="social-button-container">
								<span>w</span>
								<p>Like us on Facebook</p>
							</li>
							</a>

							<a href="">
							<li class="social-button twitter" id="social-button-container">
								<span>t</span>
								<p>&nbsp;Share with Twitter</p>
							</li>
							</a>

							<a href="">
							<li class="social-button google" id="social-button-container">
								<span>g</span>
								<p>Share with Google</p>
							</li>
							</a>
						</ul>
					</li>
				</ul>

			<br>
					<div id="copyright-footer">
						<%= link_to image_tag("BreezedigsLogo.png", size: "125x34"), root_path %>
						<p>&#169; Breezedigs. All rights reserved. Breezedigs, Dig Seeker, Dig Finder, and the Breezedigs logo are the registered trademarks of Breezedigs, Inc</p>
					</div>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_footerstaticcities.html.erb
<li id="footer-cities">
	<ul>
		<%= show_cities(0,17) %>
	</ul>
</li>

<li id="footer-cities">
	<ul>
		<%= show_cities(17,17) %>
	</ul>
</li>

<li id="footer-cities">
	<ul>
		<%= show_cities(34,17) %>
	</ul>
</li>

<li id="footer-cities">
	<ul>
		<%= show_cities(51,17) %>
	</ul>
</li>

<li id="footer-cities">
	<ul>
		<%= show_cities(68,17) %>
	</ul>
</li>

app/views/layouts/_gmaps_autozoom.html.erb
<script type="text/javascript" charset="utf-8">
  Gmaps.map.callback = function() {
    if (Gmaps.map.markers.length == 1) {
     //only one marker, choose the zoom level you expect
     setTimeout(function() { Gmaps.map.serviceObject.setZoom(14);}, 50);
    }
    else{
     //more than one marker, let's auto_zoom
     Gmaps.map.map_options.auto_zoom = true;
     Gmaps.map.adjustMapToBounds();
    }
  }
</script>

app/views/layouts/_header.html.erb
<div class="maintopbar">
	<div class="container no-wrap">
		<nav class="header-box logo-box">
			<div id="logo">
				<%= link_to(
				image_tag("BreezedigsLogo.png", 
				size: "150x41",
				alt: "Edit Entry",
				mouseover: "breezedigslogo_hover.png"), 
				root_path) 
				%>
			</div>
		</nav>

		<nav class="header-buttons">
		</nav>

		<nav class="header-box">
			<ul class="header-links">
				<li>
				<%= link_to(raw("<strong>Submit a Rent</strong>"), new_rent_path) %>
				</li>
				<li>
				<%= link_to(raw("<strong>Write a Review</strong>"), new_review_path) %>
				</li>
			<% if user_signed_in? %>
					<li><%= link_to "My Account", user_path(current_user) %></li>
					<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
			<% else %>
					<li><%= link_to "Sign up", new_user_registration_path %></li>	
					<li><%= link_to "Sign in", new_user_session_path %></li>
				</ul>
			<% end %>
		</nav>
	</div>
</div>


<% if controller.action_name != 'home' %>
	<%= render 'layouts/searchbar' %>
<% end %>

app/views/layouts/_hero.html.erb
<div class="em-buffer-4"></div>

<div class="hero">
	<div class="container">

		<div class="hero-text">
			<h1>The inside scoop on [<%= @buildings %>] apartments</h1>
		</div>

		<div class="hero-search">
			<%= form_tag buildings_path, method: :get do %>
			  
			    <%= text_field_tag :search, params[:search], placeholder: "Building name, address, street, city, zip, or neighborhood" %>

		   	<button type="submit" class="hero-search-button">
    		<i class="icon-search icon-large"></i> 
			</button>

		  	</p>
			<% end %>
		</div>

		<div class="hero-links">
			<%= link_to "Write a review", new_review_path %>
			<%= link_to "Submit a rent", new_rent_path %>
		</div>

		<!--
		<div class="hero-details">
			<ul>
				<li><h3></h3><p>Buildings</p></li>
				<li><h3></h3><p>Reviews</p></li>
				<li><h3></h3><p>Rents Prices</p></li>
			</ul>
		</div>
		-->

	</div>
</div>

<!-- <div class="home-stripe">
	<div class="container">
	
	</div>
</div> -->

app/views/layouts/_searchbar.html.erb
<div class="em-buffer-4"></div> <!-- To clear the header -->

<div class="searchbar">
	<div class="container center">
			<%= form_tag buildings_path, :method => 'get' do %>
		 	<p>
		    <%= text_field_tag :search, params[:search], placeholder: "Building name, address, street, city, zip, or neighborhood", class: "searchbar-field"%>
		    
		    <%= submit_tag "search", :name => nil, class: "btn btn-small bottom-buffer" %>
		  	</p>
			<% end %>
	</div>
</div>

app/views/layouts/_searchplaceholder.html.erb
<nav class="search">
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= javascript_include_tag "application", "rails.validations" %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

 	<!--[if lt IE 8]>
	<%= stylesheet_link_tag "font-awesome-ie7.min.css", media: "all" %>
	<![endif]-->

</head>

<body>
	<%= yield :scripts %>
	<div id="holder">

	<%= render 'layouts/header' %>	

	<div id="body">
		<%= yield %>
	</div>

<%= render 'layouts/footer' %>
</div>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-41359842-1', 'breezedigs.com');
	  ga('send', 'pageview');

	</script>

</body>
</html>